### PR TITLE
Updating the path to the paper

### PR DESCRIPTION
**Pull request by markgrover**
The original path seems to be getting redirected.

### CODE REVIEW

**Comment by markgrover** [comment]
If you think there's a better link, feel free to update it to that.

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by nlaptev** [comment]
lgtm

**Pull request merged**
