### PR TITLE
Refactored, cleaned some code

### PR DESCRIPTION
**Pull request by lbordowitz**
Code clean-ups:
- simplified boolean expressions
- removed boxing/unboxing, simplified some casts
- moved fields and variables to private, final if possible (immutability is good!)
- removed unnecessary (or pre-existing) classes, converted DoublePoint to DoublePointIdentified

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by lbordowitz** [comment]
Alright, signed it.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by lbordowitz** [comment]
Closing pull request until able to fix regression.

**Comment by lbordowitz** [comment]
Nevermind, just a config problem.

**Comment by nlaptev** [comment]
Hi Larry, for this to be merged, please take care of the merge conflicts.

**Comment by lbordowitz** [comment]
Quite a bit has changed since I made this pull request. I'm going to remove it, try again.

**Pull request closed without merging**
